#!/usr/bin/env bash
set -u

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

IPOD_TARGET_VOLUME="${IPOD_TARGET_VOLUME:-/Volumes/4 tb backup}"
IPOD_PROJECT_ROOT="${IPOD_PROJECT_ROOT:-$IPOD_TARGET_VOLUME/codex ipod ready 500gb}"
IPOD_TOTAL_TARGET_GB="${IPOD_TOTAL_TARGET_GB:-500}"
IPOD_VIDEO_TARGET_GB="${IPOD_VIDEO_TARGET_GB:-420}"
IPOD_MUSIC_TARGET_GB="${IPOD_MUSIC_TARGET_GB:-45}"
IPOD_PODCAST_TARGET_GB="${IPOD_PODCAST_TARGET_GB:-25}"
IPOD_PHOTO_TARGET_GB="${IPOD_PHOTO_TARGET_GB:-5}"
IPOD_RESERVE_TARGET_GB="${IPOD_RESERVE_TARGET_GB:-5}"

IPOD_VIDEO_QUALITY_PRESET="${IPOD_VIDEO_QUALITY_PRESET:-very-compact}"
IPOD_VIDEO_ROOT="${IPOD_VIDEO_ROOT:-$IPOD_PROJECT_ROOT/videos}"
IPOD_VIDEO_FINISH_DIR="${IPOD_VIDEO_ROOT}/finish files"
IPOD_VIDEO_LOG="${IPOD_VIDEO_ROOT}/conversion_and_tagging.log"
IPOD_VIDEO_STDOUT="${IPOD_VIDEO_STDOUT:-/tmp/ipod_convert_and_tag_500gb.out}"
IPOD_SCREEN_NAME="${IPOD_SCREEN_NAME:-ipod_500gb}"

IPOD_MUSIC_ROOT="${IPOD_MUSIC_ROOT:-$IPOD_TARGET_VOLUME/MUSIC}"
IPOD_SPOTIFY_PLAYLIST_NAME="${IPOD_SPOTIFY_PLAYLIST_NAME:-for iPod}"
IPOD_SPOTIFY_MIN_SCORE="${IPOD_SPOTIFY_MIN_SCORE:-90}"
IPOD_SPOTIFY_CLIENT_ID_DEFAULT="${IPOD_SPOTIFY_CLIENT_ID_DEFAULT:-1fd5039188e3488b940933da79591fe1}"

IPOD_PODCAST_STAGE_DIR="${IPOD_PODCAST_STAGE_DIR:-$IPOD_PROJECT_ROOT/podcasts/MSSP}"
IPOD_PODCAST_MANIFEST="${IPOD_PODCAST_MANIFEST:-$IPOD_PROJECT_ROOT/podcasts/mssp_manifest.tsv}"

IPOD_PHOTO_SOURCE_DIR="${IPOD_PHOTO_SOURCE_DIR:-$HOME/Pictures/iPod Photos Source}"
IPOD_PHOTO_STAGE_DIR="${IPOD_PHOTO_STAGE_DIR:-$IPOD_PROJECT_ROOT/photos}"

IPOD_LOCAL_STATE_DIR="${IPOD_LOCAL_STATE_DIR:-$HOME/.codex/ipod-supervisor}"
IPOD_STATUS_DIR="${IPOD_STATUS_DIR:-$IPOD_LOCAL_STATE_DIR}"
IPOD_STATUS_REPORT="${IPOD_STATUS_REPORT:-$IPOD_LOCAL_STATE_DIR/progress_report.txt}"
IPOD_PROGRESS_HISTORY="${IPOD_PROGRESS_HISTORY:-$IPOD_LOCAL_STATE_DIR/progress_history.tsv}"
IPOD_DESKTOP_NOTE="${IPOD_DESKTOP_NOTE:-$HOME/Desktop/IPOD PROJECT STATUS.txt}"
IPOD_PIPELINE_LOG="${IPOD_PIPELINE_LOG:-$IPOD_LOCAL_STATE_DIR/stage_pipeline.log}"
IPOD_PIPELINE_LOCK_DIR="${IPOD_PIPELINE_LOCK_DIR:-$IPOD_LOCAL_STATE_DIR/.stage_pipeline.lock}"
IPOD_DAILY_NOTE_STAMP="${IPOD_DAILY_NOTE_STAMP:-$IPOD_LOCAL_STATE_DIR/.daily_note_last_shown}"
IPOD_DAILY_NOTE_HOUR="${IPOD_DAILY_NOTE_HOUR:-12}"
IPOD_DAILY_NOTE_MINUTE="${IPOD_DAILY_NOTE_MINUTE:-0}"
IPOD_PAUSE_FLAG="${IPOD_PAUSE_FLAG:-$IPOD_STATUS_DIR/pause_requested.flag}"
IPOD_SPOTIFY_REPORT="${IPOD_SPOTIFY_REPORT:-$IPOD_LOCAL_STATE_DIR/spotify_liked_report.json}"
IPOD_SPOTIFY_LOG="${IPOD_SPOTIFY_LOG:-$IPOD_LOCAL_STATE_DIR/spotify_liked.log}"
IPOD_PODCAST_LOG="${IPOD_PODCAST_LOG:-$IPOD_LOCAL_STATE_DIR/mssp_stage.log}"
IPOD_PHOTO_LOG="${IPOD_PHOTO_LOG:-$IPOD_LOCAL_STATE_DIR/photo_stage.log}"
IPOD_SUPERVISOR_LOG="${IPOD_SUPERVISOR_LOG:-$IPOD_LOCAL_STATE_DIR/supervisor.log}"
IPOD_SUPERVISOR_PID_FILE="${IPOD_SUPERVISOR_PID_FILE:-$IPOD_LOCAL_STATE_DIR/supervisor.pid}"

IPOD_AUTORUN_DISABLE_FINAL_SYNC="${IPOD_AUTORUN_DISABLE_FINAL_SYNC:-1}"

ipod_ensure_project_dirs() {
  mkdir -p \
    "$IPOD_STATUS_DIR" \
    "$IPOD_PHOTO_SOURCE_DIR"

  if [[ -d "$IPOD_TARGET_VOLUME" ]]; then
    mkdir -p \
      "$IPOD_PROJECT_ROOT" \
      "$IPOD_VIDEO_ROOT" \
      "$IPOD_VIDEO_FINISH_DIR" \
      "$(dirname "$IPOD_PODCAST_MANIFEST")" \
      "$IPOD_PODCAST_STAGE_DIR" \
      "$IPOD_PHOTO_STAGE_DIR"
  fi
}
